// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvtnzixsxfjzwhjetrfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dG56aXhzeGZqendoamV0cmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDk1MzgsImV4cCI6MjA2NDcyNTUzOH0.DLyQG7Hfgcwacd87FCRp51j11RNQMjDiP5jzos3DEKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);